#!/bin/sh

while true; do
	xsetroot -name " $(setxkbmap -query | grep layout | sed 's/ //g')  $(free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')  $(date "+%T %e.%m.%Y")"
	sleep 1
done
